import {
  DATASET_VERSION,
  type AuditDataset,
  type AuditFact,
  type CompanySnapshot,
  type EvidenceItem,
  type EvidenceMethod,
  type EvidenceStrength,
  type FactValue,
} from './types';

const observedAt = '2026-08-30T08:00:00.000Z';

const evidence = (
  id: string,
  label: string,
  method: EvidenceMethod,
  strength: EvidenceStrength = 'strong',
): EvidenceItem => ({ id, label, method, strength, observedAt });

const fact = (
  key: string,
  value: FactValue,
  evidenceId: string,
): AuditFact => ({
  key,
  value,
  evidenceIds: [evidenceId],
});

const makeCompany = (
  base: Pick<CompanySnapshot, 'id' | 'name' | 'domain' | 'industry'>,
  groups: Array<{
    evidence: EvidenceItem;
    facts: Array<[string, FactValue]>;
  }>,
): CompanySnapshot => ({
  ...base,
  city: 'Göteborg',
  capturedAt: observedAt,
  evidence: groups.map((group) => group.evidence),
  facts: groups.flatMap((group) =>
    group.facts.map(([key, value]) => fact(key, value, group.evidence.id)),
  ),
  tags: ['demo', 'syntetisk'],
  reviews: [],
});

export const SAMPLE_DATASET: AuditDataset = {
  version: DATASET_VERSION,
  name: 'Syntetisk demonstrationskö',
  createdAt: '2026-08-30T09:00:00.000Z',
  companies: [
    makeCompany(
      {
        id: 'demo-linne-bageri',
        name: 'Demo: Linné Bageri',
        domain: 'linne-bageri.example',
        industry: 'Bageri',
      },
      [
        {
          evidence: evidence(
            'linne-http',
            'Syntetiskt HTTP- och headerprov',
            'headers',
          ),
          facts: [
            ['availability.reachable', true],
            ['availability.http_status', 200],
            ['transport.https_enabled', true],
            ['transport.tls_valid', true],
            ['transport.redirect_hops', 2],
            ['transport.redirect_loop', false],
            ['transport.mixed_content_count', 0],
            ['transport.host_variants_converge', true],
            ['security.hsts_present', false],
            ['security.csp_present', false],
            ['security.nosniff_present', true],
            ['security.directory_listing_detected', false],
            ['security.stack_trace_exposed', false],
          ],
        },
        {
          evidence: evidence(
            'linne-crawl',
            'Syntetisk HTML- och länköversikt',
            'html',
          ),
          facts: [
            ['crawl.robots_blocks_home', false],
            ['crawl.home_noindex', false],
            ['crawl.sitemap_present', true],
            ['crawl.sitemap_valid', true],
            ['crawl.home_canonical_present', true],
            ['crawl.home_canonical_count', 1],
            ['crawl.home_canonical_off_domain', false],
            ['crawl.broken_internal_links', 2],
            ['crawl.orphan_page_count', 0],
            ['crawl.max_priority_page_depth', 3],
            ['seo.title_present', true],
            ['seo.title_length', 18],
            ['seo.meta_description_present', false],
            ['seo.duplicate_title_page_count', 1],
            ['seo.thin_priority_page_count', 0],
            ['seo.structured_data_error_count', 2],
            ['seo.open_graph_complete', false],
          ],
        },
        {
          evidence: evidence(
            'linne-lighthouse',
            'Syntetiskt mobiltest',
            'lighthouse',
          ),
          facts: [
            ['performance.mobile_lcp_ms', 4860],
            ['performance.mobile_inp_ms', 310],
            ['performance.mobile_cls', 0.31],
            ['performance.mobile_ttfb_ms', 940],
            ['performance.mobile_tbt_ms', 680],
            ['performance.total_transfer_kb', 4320],
            ['performance.javascript_transfer_kb', 1120],
            ['performance.image_transfer_kb', 2480],
            ['performance.oversized_image_count', 4],
            ['performance.uncompressed_text_resource_count', 0],
          ],
        },
        {
          evidence: evidence(
            'linne-layout',
            'Syntetisk skärmbild och layoutmätning',
            'screenshot',
          ),
          facts: [
            ['mobile.viewport_meta_present', true],
            ['mobile.horizontal_overflow_px', 18],
            ['mobile.small_tap_target_count', 5],
            ['mobile.small_text_count', 2],
            ['mobile.navigation_usable', true],
            ['mobile.blocking_overlay', false],
            ['mobile.form_overflow_count', 0],
            ['mobile.media_overflow_count', 1],
            ['mobile.sticky_coverage_percent', 22],
            ['mobile.orientation_locked', false],
            ['a11y.html_lang_present', true],
            ['a11y.h1_count', 1],
            ['a11y.heading_skip_count', 2],
            ['a11y.missing_alt_count', 3],
            ['a11y.unnamed_control_count', 1],
            ['a11y.unlabelled_field_count', 0],
            ['a11y.contrast_failure_count', 4],
            ['a11y.keyboard_trap_count', 0],
            ['a11y.focus_visible', false],
            ['a11y.uncaptioned_video_count', 0],
          ],
        },
        {
          evidence: evidence(
            'linne-business',
            'Syntetisk företags- och konverteringsobservation',
            'manual',
            'medium',
          ),
          facts: [
            ['business.public_phone_present', true],
            ['business.public_email_present', true],
            ['business.has_public_opening_hours', true],
            ['business.has_visit_location', true],
            ['business.serves_multiple_areas', false],
            ['business.accepts_booking', false],
            ['business.has_ecommerce', false],
            ['local.location_clarity', true],
            ['local.nap_complete', true],
            ['local.nap_conflict_count', 0],
            ['local.local_business_schema_present', false],
            ['local.opening_hours_present', true],
            ['local.opening_hours_conflict', false],
            ['local.directions_link_present', false],
            ['local.profile_website_mismatch', false],
            ['conversion.primary_cta_present', true],
            ['conversion.primary_cta_above_fold', true],
            ['conversion.cta_copy_clear', false],
            ['conversion.contact_click_depth', 3],
            ['conversion.phone_link_present', false],
            ['conversion.email_link_present', true],
            ['conversion.primary_nav_item_count', 10],
            ['conversion.broken_cta_count', 1],
            ['conversion.offer_clarity', true],
            ['conversion.primary_cta_variant_count', 4],
            ['content.placeholder_text_count', 0],
            ['content.broken_image_count', 1],
            ['content.encoding_error_count', 0],
            ['content.stale_statement_count', 1],
            ['trust.business_identity_clear', true],
            ['trust.contact_page_present', true],
            ['trust.about_information_present', false],
            ['trust.unsupported_claim_count', 0],
            ['trust.unattributed_testimonial_count', 0],
            ['trust.broken_social_link_count', 1],
          ],
        },
        {
          evidence: evidence(
            'linne-form',
            'Syntetisk formulärobservation',
            'browser-test',
          ),
          facts: [
            ['forms.any_form_present', true],
            ['forms.contact_form_present', true],
            ['forms.contact_submission_success', true],
            ['forms.success_confirmation_clear', true],
            ['forms.validation_errors_clear', false],
            ['forms.required_field_count', 9],
            ['privacy.collects_personal_data', true],
            ['privacy.nonessential_tracking_present', true],
            ['privacy.policy_present', true],
            ['privacy.consent_ui_present', false],
            ['privacy.tracking_before_choice_count', 2],
            ['security.form_actions_https', true],
          ],
        },
        {
          evidence: evidence(
            'linne-ops',
            'Syntetisk HTML-kontroll',
            'html',
          ),
          facts: [
            ['operations.helpful_404_present', false],
            ['operations.console_error_count', 2],
            ['operations.broken_external_link_count', 1],
            ['operations.favicon_present', true],
            ['operations.html_validation_error_count', 14],
            ['operations.broken_priority_route_count', 0],
            ['operations.duplicate_analytics_count', 1],
            ['operations.known_critical_client_dependency_count', 0],
            ['operations.invalid_mailto_count', 0],
            ['operations.invalid_tel_count', 1],
          ],
        },
      ],
    ),
    makeCompany(
      {
        id: 'demo-hisingen-cykel',
        name: 'Demo: Hisingens Cykel',
        domain: 'hisingen-cykel.example',
        industry: 'Cykelverkstad',
      },
      [
        {
          evidence: evidence('cykel-http', 'Syntetiskt HTTP-prov', 'headers'),
          facts: [
            ['availability.reachable', true],
            ['availability.http_status', 200],
            ['transport.https_enabled', true],
            ['transport.tls_valid', true],
            ['transport.redirect_hops', 1],
            ['transport.redirect_loop', false],
            ['transport.mixed_content_count', 1],
            ['transport.host_variants_converge', false],
          ],
        },
        {
          evidence: evidence('cykel-html', 'Syntetisk sidobservation', 'html'),
          facts: [
            ['crawl.robots_blocks_home', false],
            ['crawl.home_noindex', false],
            ['crawl.sitemap_present', false],
            ['crawl.home_canonical_present', false],
            ['crawl.broken_internal_links', 0],
            ['seo.title_present', true],
            ['seo.title_length', 42],
            ['seo.meta_description_present', true],
            ['seo.meta_description_length', 138],
            ['seo.duplicate_title_page_count', 0],
            ['seo.open_graph_complete', true],
            ['content.placeholder_text_count', 0],
            ['content.broken_image_count', 0],
            ['trust.business_identity_clear', true],
            ['trust.contact_page_present', true],
          ],
        },
        {
          evidence: evidence(
            'cykel-manual',
            'Syntetisk manuell genomgång',
            'manual',
            'medium',
          ),
          facts: [
            ['business.public_phone_present', true],
            ['business.public_email_present', false],
            ['business.has_public_opening_hours', true],
            ['business.has_visit_location', true],
            ['business.serves_multiple_areas', false],
            ['business.accepts_booking', true],
            ['business.has_ecommerce', false],
            ['local.location_clarity', false],
            ['local.nap_complete', false],
            ['local.nap_conflict_count', 1],
            ['local.local_business_schema_present', false],
            ['local.opening_hours_present', false],
            ['local.directions_link_present', true],
            ['local.profile_website_mismatch', false],
            ['conversion.primary_cta_present', false],
            ['conversion.contact_click_depth', 4],
            ['conversion.phone_link_present', true],
            ['conversion.primary_nav_item_count', 6],
            ['conversion.broken_cta_count', 0],
            ['conversion.offer_clarity', false],
            ['conversion.primary_cta_variant_count', 0],
            ['commerce.booking_path_works', false],
            ['commerce.booking_mobile_usable', false],
          ],
        },
      ],
    ),
    makeCompany(
      {
        id: 'demo-majorna-studio',
        name: 'Demo: Majorna Studio',
        domain: 'majorna-studio.example',
        industry: 'Fotostudio',
      },
      [
        {
          evidence: evidence(
            'studio-core',
            'Syntetisk komplett kärnkontroll',
            'html',
          ),
          facts: [
            ['availability.reachable', true],
            ['availability.http_status', 200],
            ['transport.https_enabled', true],
            ['transport.tls_valid', true],
            ['transport.redirect_hops', 0],
            ['transport.redirect_loop', false],
            ['transport.mixed_content_count', 0],
            ['transport.host_variants_converge', true],
            ['crawl.robots_blocks_home', false],
            ['crawl.home_noindex', false],
            ['crawl.sitemap_present', true],
            ['crawl.sitemap_valid', true],
            ['crawl.home_canonical_present', true],
            ['crawl.home_canonical_count', 1],
            ['crawl.home_canonical_off_domain', false],
            ['crawl.broken_internal_links', 0],
            ['seo.title_present', true],
            ['seo.title_length', 48],
            ['seo.meta_description_present', true],
            ['seo.meta_description_length', 145],
            ['seo.duplicate_title_page_count', 0],
            ['seo.structured_data_error_count', 0],
            ['seo.open_graph_complete', true],
          ],
        },
        {
          evidence: evidence(
            'studio-ux',
            'Syntetisk mobil- och konverteringskontroll',
            'screenshot',
          ),
          facts: [
            ['mobile.viewport_meta_present', true],
            ['mobile.horizontal_overflow_px', 0],
            ['mobile.small_tap_target_count', 0],
            ['mobile.small_text_count', 0],
            ['mobile.navigation_usable', true],
            ['mobile.blocking_overlay', false],
            ['mobile.media_overflow_count', 0],
            ['a11y.html_lang_present', true],
            ['a11y.h1_count', 1],
            ['a11y.heading_skip_count', 0],
            ['a11y.missing_alt_count', 0],
            ['a11y.unnamed_control_count', 0],
            ['a11y.contrast_failure_count', 0],
            ['a11y.keyboard_trap_count', 0],
            ['a11y.focus_visible', true],
            ['business.public_phone_present', true],
            ['business.public_email_present', true],
            ['conversion.primary_cta_present', true],
            ['conversion.primary_cta_above_fold', true],
            ['conversion.cta_copy_clear', true],
            ['conversion.contact_click_depth', 1],
            ['conversion.phone_link_present', true],
            ['conversion.email_link_present', true],
            ['conversion.primary_nav_item_count', 5],
            ['conversion.broken_cta_count', 0],
            ['conversion.offer_clarity', true],
            ['conversion.primary_cta_variant_count', 1],
          ],
        },
      ],
    ),
    makeCompany(
      {
        id: 'demo-vasastan-redovisning',
        name: 'Demo: Vasastans Redovisning',
        domain: 'vasastan-redovisning.example',
        industry: 'Redovisning',
      },
      [
        {
          evidence: evidence(
            'redo-minimal',
            'Syntetiskt begränsat manuellt underlag',
            'manual',
            'weak',
          ),
          facts: [
            ['availability.reachable', true],
            ['availability.http_status', 200],
            ['transport.https_enabled', true],
            ['conversion.primary_cta_present', true],
            ['conversion.offer_clarity', false],
          ],
        },
      ],
    ),
  ],
};

export const SAMPLE_JSON = JSON.stringify(SAMPLE_DATASET, null, 2);
